### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by l0go** [l0go/haxeget#1]
Not a windows user myself, but this would probably be very helpful to some people. If you have an interest in working on this, please tell me! I can try to help in any way I can, even if you don't know Rust.

**Comment by AltronMaxX** [comment]
I've done Windows support in my fork, but I'm not sure yet if it works the way it should. It will also take time to test the work and explore the possibility of executing the program from any directory.
https://github.com/AltronMaxX/haxeget/tree/feature/windows_support

**Comment by l0go** [comment]
> I've done Windows support in my fork, but I'm not sure yet if it works the way it should. It will also take time to test the work and explore the possibility of executing the program from any directory. https://github.com/AltronMaxX/haxeget/tree/feature/windows_support

Thanks so much!I was dreading having to implement this myself. Hopefully the code base wasn't too hard to navigate... What do you mean by "executing the program from any directory." Do you mean ``haxeget`` itself? If so, I assume making an installer using something like [cargo-wix](https://github.com/volks73/cargo-wix) would solve that? Could you create a PR so we can discuss over there? I'm excited!

**Comment by l0go** [comment]
@AltronMaxX

**Comment by AltronMaxX** [comment]
>
> Do you mean `haxeget` itself? 

Yes, I meant this.

**Comment by l0go** [comment]
Solved by @AltronMaxX
