### ISSUE TITLE
help with use

### ISSUE THREAD

**Issue by taufei** [l0go/haxeget#11]
im very sorry if this is a really fucking basic thing but i cannot for the life of me understand how to work this
![image](https://github.com/l0go/haxeget/assets/111521802/9ed76a8a-c55b-4f81-a289-d7da5f054425)

**Comment by JonnycatMeow** [comment]
you gotta use the edit system variables thing

**Comment by l0go** [comment]
Closing as the previous message answers your question, if you need further help feel free to reopen :)
