### ISSUE TITLE
`haxe` in `.haxeget` is inacessible (Windows)

### ISSUE THREAD

**Issue by doggogit** [l0go/haxeget#12]
Wanted to try this `haxeget` project out, running into a few issues which I found a "solution" to.

Used the `Cargo` method to install `haxeget` and after installing Haxe 4.3.3 and adding it to PATH variables, the terminal still spewed out an error that there is no such command.

Looking into `%HAXEPATH%`, it puts the folder as `C:\.haxeget\haxe`, however, upon trying to open the folder, it says it's an invalid location.

![image](https://github.com/l0go/haxeget/assets/115869532/9806c978-7175-4348-bb88-3e652bc0010a),

The "fix" to this was setting the `%HAXEPATH` folder to `C:\.haxeget\bin\haxe_20231117191750_de28889`.

![WindowsTerminal_RxB8TvBCsz](https://github.com/l0go/haxeget/assets/115869532/631fa57f-87e8-4a5d-bb22-af93fdadec9d)

Opened an issue 'cause I'm not sure whether or not *I'm* doing something wrong or there's something wrong with the way it installs.

**Comment by l0go** [comment]
Please try updating and see if it fixes your problem.

**Comment by doggogit** [comment]
Sorry, I don't check my GitHub periodically so that's why I couldn't respond, will test now!

**Comment by doggogit** [comment]
> ![image](https://private-user-images.githubusercontent.com/115869532/310543194-d5cb179f-48bb-452f-99a6-9dca9e764acd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mzc0MjYsIm5iZiI6MTcwOTczNzEyNiwicGF0aCI6Ii8xMTU4Njk1MzIvMzEwNTQzMTk0LWQ1Y2IxNzlmLTQ4YmItNDUyZi05OWE2LTlkY2E5ZTc2NGFjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNDU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzUzYjkxN2I4MjI2NGUwZjI4MmMwZDE4YmZmMjg3YzA4MTZjNjA5OTk2M2ZiYjgwNGRiODE0OTQ5MDk3MTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O8BDlC11PEevKJ6G2G46huA3tvV_2lJNnfn2_9_eN88)
> 
> Got this error.

# Okay, update. This is getting really weird.

- I managed to install `nightly` through Command Prompt, however, the same error gets spat out in Windows Terminal.
- Installing `4.3.3` in Command Prompt doesn't work and spits out the same error as above.
-------------------------------------------

## Fixed the "issue" below by running `haxeget.exe install neko`.
~~# In terms of `nightly`:~~
~~- Typing out `haxe` prints out all the commands that can be used.~~
~~- However, typing out `haxelib install lime` spits out this error.~~
~~![image](https://github.com/l0go/haxeget/assets/115869532/0d72a7ce-7f31-4d80-942e-a3168e2feef6)~~

**Comment by l0go** [comment]
Gonna close this as most of the problems are a side effect of cargo installation. Reopen if needed.
